/*
 * Copyright (c) 2025 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.quartz.buzz.amTurnMetrics

import com.vitorpamplona.quartz.nip01Core.core.Event
import com.vitorpamplona.quartz.nip01Core.core.hexToByteArray
import com.vitorpamplona.quartz.nip01Core.crypto.KeyPair
import com.vitorpamplona.quartz.nip01Core.signers.NostrSignerInternal
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Cross-implementation compliance for the Agent Turn Metric (NIP-AM, kind:44200).
 *
 * The fixture `resources/buzz/turn_metric_vector.json` is a real event generated by
 * Buzz's own `buzz-core` code (see `crates/buzz-core/examples/gen_turn_metric.rs`) with
 * deterministic keys (owner sk=1, agent sk=2). This test proves Quartz reads Buzz's
 * events end-to-end: EventFactory dispatch → NIP-44 v2 decryption → payload schema.
 */
class AgentTurnMetricVectorTest {
    private val vector =
        Json
            .parseToJsonElement(
                AgentTurnMetricVectorTest::class.java
                    .getResourceAsStream("/buzz/turn_metric_vector.json")!!
                    .readBytes()
                    .decodeToString(),
            ).jsonObject

    private fun signer(skHex: String) = NostrSignerInternal(KeyPair(skHex.hexToByteArray()))

    private fun parsedEvent(): AgentTurnMetricEvent {
        val eventJson = vector["event"]!!.jsonObject.toString()
        val event = Event.fromJson(eventJson)
        assertTrue(event is AgentTurnMetricEvent, "EventFactory should dispatch kind 44200 to AgentTurnMetricEvent")
        return event
    }

    @Test
    fun dispatchesAndReadsTags() {
        val event = parsedEvent()
        assertEquals(44200, event.kind)
        assertEquals("79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798", event.ownerPubKey())
        assertEquals("c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5", event.agentPubKey())
        assertEquals(event.pubKey, event.agentPubKey())
    }

    @Test
    fun ownerDecryptsBuzzEvent() =
        runBlocking {
            val payload = parsedEvent().decrypt(signer(OWNER_SK))

            assertEquals("goose", payload.harness)
            assertEquals("claude-sonnet-4-5", payload.model)
            assertEquals("2026-07-01T20:11:03.213Z", payload.timestamp)
            assertEquals("12345678-1234-1234-1234-123456789abc", payload.channelId)
            assertEquals("sess-abc", payload.sessionId)
            assertEquals("turn-1", payload.turnId)
            assertEquals(1L, payload.turnSeq)
            assertTrue(payload.deltaReliable)
            assertEquals(StopReason.END_TURN, payload.stopReasonOrUnknown())

            assertEquals(1234L, payload.turn?.inputTokens)
            assertEquals(567L, payload.turn?.outputTokens)
            assertEquals(1801L, payload.turn?.totalTokens)
            assertEquals(0.0123, payload.turn?.costUsd)
            assertEquals(null, payload.turn?.cacheReadTokens)

            assertEquals(55086L, payload.cumulative?.totalTokens)
            assertEquals(0.41, payload.cumulative?.costUsd)

            assertTrue(payload.isValid())
        }

    @Test
    fun agentAlsoDecrypts() =
        runBlocking {
            // NIP-44 conversation key is symmetric, so the agent (author) reads it too.
            val payload = parsedEvent().decrypt(signer(AGENT_SK))
            assertEquals("goose", payload.harness)
        }

    @Test
    fun quartzRoundTripReadableByOwner() =
        runBlocking {
            val original = parsedEvent().decrypt(signer(OWNER_SK))
            val agent = signer(AGENT_SK)
            val ownerPub = "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"

            val rebuilt = AgentTurnMetricEvent.create(original, ownerPub, agent)
            assertEquals(44200, rebuilt.kind)
            assertNotNull(rebuilt.ownerPubKey())

            val redecrypted = rebuilt.decrypt(signer(OWNER_SK))
            assertEquals(original, redecrypted)
        }

    companion object {
        private const val OWNER_SK = "0000000000000000000000000000000000000000000000000000000000000001"
        private const val AGENT_SK = "0000000000000000000000000000000000000000000000000000000000000002"
    }
}
