#!/bin/bash

GREEN='\033[0;32m'
NO_COLOR='\033[0m'

echo "*********************************************************"
echo "Running git pre-push hook."
echo "*********************************************************"
echo ""
echo "Java Version: "
echo "$JAVA_HOME"
echo "$(java -version)"
echo "Running test... "

if [ "${CLAUDE_CODE_REMOTE:-}" = "true" ]; then
  ./gradlew test --quiet -x :desktopApp:test -x :desktopApp:upxDownload -x :desktopApp:vlcDownload
else
  ./gradlew test --quiet
fi
status=$?

if [ "$status" = 0 ] ; then
    echo "All test passed."
    exit 0
else
    echo "*********************************************************"
    echo 1>&2 "Failing test"
    printf "Run ${GREEN}./gradlew test${NO_COLOR} to make sure you have all tests green before pushing...\n"
    echo "*********************************************************"
    exit 1
fi
