/*
 * Copyright (c) 2025 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.amethyst.commons.icons.symbols

// Generated from Material Symbols Outlined codepoints.
// Source: github.com/google/material-design-icons/variablefont

object MaterialSymbols {
    val AccountBalanceWallet = MaterialSymbol("\uE850")
    val AccountCircle = MaterialSymbol("\uF20B")
    val Add = MaterialSymbol("\uE145")
    val AddCircle = MaterialSymbol("\uE3BA")
    val AddPhotoAlternate = MaterialSymbol("\uE43E")
    val AddReaction = MaterialSymbol("\uE1D3")
    val AlternateEmail = MaterialSymbol("\uE0E6")
    val Apps = MaterialSymbol("\uE5C3")
    val ArrowDownward = MaterialSymbol("\uE5DB")
    val ArrowUpward = MaterialSymbol("\uE5D8")
    val Assistant = MaterialSymbol("\uE39F")
    val AttachFile = MaterialSymbol("\uE226")
    val AttachMoney = MaterialSymbol("\uE227")
    val AudioFile = MaterialSymbol("\uEB82")
    val AutoAwesome = MaterialSymbol("\uE65F")
    val Block = MaterialSymbol("\uF08C")
    val BluetoothAudio = MaterialSymbol("\uE60F")
    val Bolt = MaterialSymbol("\uEA0B")
    val Bookmark = MaterialSymbol("\uE8E7")
    val BookmarkAdd = MaterialSymbol("\uE598")
    val BookmarkBorder = MaterialSymbol("\uE8E7")
    val BookmarkRemove = MaterialSymbol("\uE59A")
    val Forward10 = MaterialSymbol("\uE056")
    val Replay10 = MaterialSymbol("\uE059")
    val CalendarMonth = MaterialSymbol("\uEBCC")
    val Call = MaterialSymbol("\uF0D4")
    val CallEnd = MaterialSymbol("\uF0BC")
    val CameraAlt = MaterialSymbol("\uE412")
    val CameraFront = MaterialSymbol("\uF2C9")
    val CameraRear = MaterialSymbol("\uF2C8")
    val Cancel = MaterialSymbol("\uE888")
    val CellTower = MaterialSymbol("\uEBBA")
    val Chat = MaterialSymbol("\uE0C9")
    val Check = MaterialSymbol("\uE5CA")
    val CheckCircle = MaterialSymbol("\uF0BE")
    val Checklist = MaterialSymbol("\uE6B1")
    val ChevronRight = MaterialSymbol("\uE5CC")
    val Circle = MaterialSymbol("\uEF4A")
    val Clear = MaterialSymbol("\uE5CD")
    val Close = MaterialSymbol("\uE5CD")
    val CloudDownload = MaterialSymbol("\uE2C0")
    val CloudSync = MaterialSymbol("\uEB5A")
    val CloudUpload = MaterialSymbol("\uE2C3")
    val Code = MaterialSymbol("\uE86F")
    val Collections = MaterialSymbol("\uE3D3")
    val CollectionsBookmark = MaterialSymbol("\uE431")
    val ContentCopy = MaterialSymbol("\uE14D")
    val ContentPaste = MaterialSymbol("\uE14F")
    val CurrencyBitcoin = MaterialSymbol("\uEBC5")
    val Dashboard = MaterialSymbol("\uE871")
    val DateRange = MaterialSymbol("\uE916")
    val Delete = MaterialSymbol("\uE92E")
    val DeleteForever = MaterialSymbol("\uE92B")
    val DeleteSweep = MaterialSymbol("\uE16C")
    val Description = MaterialSymbol("\uE873")
    val Dns = MaterialSymbol("\uE875")
    val Done = MaterialSymbol("\uE876")
    val DoneAll = MaterialSymbol("\uE877")
    val Download = MaterialSymbol("\uF090")
    val DownloadForOffline = MaterialSymbol("\uF000")
    val Downloading = MaterialSymbol("\uF001")
    val Drafts = MaterialSymbol("\uE151")
    val DragIndicator = MaterialSymbol("\uE945")
    val Edit = MaterialSymbol("\uF097")
    val EditNote = MaterialSymbol("\uE745")
    val EditOff = MaterialSymbol("\uE950")
    val Email = MaterialSymbol("\uE159")
    val EmojiEmotions = MaterialSymbol("\uEA22")
    val Error = MaterialSymbol("\uF8B6")
    val ErrorOutline = MaterialSymbol("\uF8B6")
    val ExpandLess = MaterialSymbol("\uE5CE")
    val ExpandMore = MaterialSymbol("\uE5CF")
    val Explore = MaterialSymbol("\uE87A")
    val Extension = MaterialSymbol("\uE87B")
    val Face = MaterialSymbol("\uF008")
    val Favorite = MaterialSymbol("\uE87E")
    val FavoriteBorder = MaterialSymbol("\uE87E")
    val FileOpen = MaterialSymbol("\uEAF3")
    val FilterAlt = MaterialSymbol("\uEF4F")
    val FolderZip = MaterialSymbol("\uEB2C")
    val FormatBold = MaterialSymbol("\uE238")
    val FormatItalic = MaterialSymbol("\uE23F")
    val FormatListNumbered = MaterialSymbol("\uE242")
    val FormatQuote = MaterialSymbol("\uE244")
    val FormatStrikethrough = MaterialSymbol("\uE246")
    val Forum = MaterialSymbol("\uE8AF")
    val Forward = MaterialSymbol("\uF57A")
    val Fullscreen = MaterialSymbol("\uE5D0")
    val FullscreenExit = MaterialSymbol("\uE5D1")
    val Gavel = MaterialSymbol("\uE90E")
    val Group = MaterialSymbol("\uEA21")
    val GroupAdd = MaterialSymbol("\uE7F0")
    val Groups = MaterialSymbol("\uF233")
    val Hearing = MaterialSymbol("\uE023")
    val History = MaterialSymbol("\uE8B3")
    val Home = MaterialSymbol("\uE9B2")
    val HorizontalRule = MaterialSymbol("\uF108")
    val HourglassBottom = MaterialSymbol("\uEA5C")
    val HourglassEmpty = MaterialSymbol("\uE88B")
    val HourglassTop = MaterialSymbol("\uEA5B")
    val Image = MaterialSymbol("\uE3F4")
    val Key = MaterialSymbol("\uE73C")
    val KeyboardArrowDown = MaterialSymbol("\uE313")
    val KeyboardArrowUp = MaterialSymbol("\uE316")
    val Language = MaterialSymbol("\uE894")
    val Link = MaterialSymbol("\uE250")
    val LocationOff = MaterialSymbol("\uE0C7")
    val LocationOn = MaterialSymbol("\uF1DB")
    val Lock = MaterialSymbol("\uE899")
    val LockOpen = MaterialSymbol("\uE898")
    val Mail = MaterialSymbol("\uE159")
    val MenuBook = MaterialSymbol("\uEA19")
    val Mic = MaterialSymbol("\uE31D")
    val MicOff = MaterialSymbol("\uE02B")
    val MilitaryTech = MaterialSymbol("\uEA3F")
    val MoreVert = MaterialSymbol("\uE5D4")
    val MoveToInbox = MaterialSymbol("\uE168")
    val MusicNote = MaterialSymbol("\uE405")
    val News = MaterialSymbol("\uE032")
    val NoAccounts = MaterialSymbol("\uF03E")
    val NoEncryption = MaterialSymbol("\uF03F")
    val Notifications = MaterialSymbol("\uE7F5")
    val Numbers = MaterialSymbol("\uEAC7")
    val OpenInBrowser = MaterialSymbol("\uE89D")
    val OpenInFull = MaterialSymbol("\uF1CE")
    val Paid = MaterialSymbol("\uF041")
    val PanTool = MaterialSymbol("\uE925")
    val Pause = MaterialSymbol("\uE034")
    val PauseCircleOutline = MaterialSymbol("\uE1A2")
    val Payment = MaterialSymbol("\uE8A1")
    val People = MaterialSymbol("\uEA21")
    val Person = MaterialSymbol("\uF0D3")
    val PersonAdd = MaterialSymbol("\uEA4D")
    val PersonOff = MaterialSymbol("\uE510")
    val PersonRemove = MaterialSymbol("\uEF66")
    val Phone = MaterialSymbol("\uF0D4")
    val Photo = MaterialSymbol("\uE432")
    val PictureAsPdf = MaterialSymbol("\uE415")
    val PictureInPicture = MaterialSymbol("\uE8AA")
    val PlayArrow = MaterialSymbol("\uE037")
    val PlayCircle = MaterialSymbol("\uE1C4")
    val PlayCircleOutline = MaterialSymbol("\uE1C4")
    val Poll = MaterialSymbol("\uF0CC")
    val PrivacyTip = MaterialSymbol("\uF0DC")
    val Public = MaterialSymbol("\uE80B")
    val PublicOff = MaterialSymbol("\uF1CA")
    val PushPin = MaterialSymbol("\uF10D")
    val RadioButtonChecked = MaterialSymbol("\uE837")
    val RadioButtonUnchecked = MaterialSymbol("\uE836")
    val Recommend = MaterialSymbol("\uE9D2")
    val Refresh = MaterialSymbol("\uE5D5")
    val RemoveCircleOutline = MaterialSymbol("\uF08F")
    val RemoveDone = MaterialSymbol("\uE9D3")
    val Replay = MaterialSymbol("\uE042")
    val Report = MaterialSymbol("\uF052")
    val Save = MaterialSymbol("\uE161")
    val SaveAlt = MaterialSymbol("\uF090")
    val Schedule = MaterialSymbol("\uEFD6")
    val Science = MaterialSymbol("\uEA4B")
    val Search = MaterialSymbol("\uE8B6")
    val Security = MaterialSymbol("\uE32A")
    val Sensors = MaterialSymbol("\uE51E")
    val Settings = MaterialSymbol("\uE8B8")
    val SettingsInputAntenna = MaterialSymbol("\uE8BF")
    val Share = MaterialSymbol("\uE80D")
    val Shield = MaterialSymbol("\uE9E0")
    val SkipNext = MaterialSymbol("\uE044")
    val SkipPrevious = MaterialSymbol("\uE045")
    val SmartDisplay = MaterialSymbol("\uF06A")
    val SportsEsports = MaterialSymbol("\uEA28")
    val Star = MaterialSymbol("\uF09A")
    val StarBorder = MaterialSymbol("\uF09A")
    val Stop = MaterialSymbol("\uE047")
    val Storage = MaterialSymbol("\uE1DB")
    val Storefront = MaterialSymbol("\uEA12")
    val Subscriptions = MaterialSymbol("\uE064")
    val SwapHoriz = MaterialSymbol("\uE8D4")
    val Sync = MaterialSymbol("\uE627")
    val SyncProblem = MaterialSymbol("\uE629")
    val Tag = MaterialSymbol("\uE9EF")
    val ThumbUp = MaterialSymbol("\uF577")
    val Timer = MaterialSymbol("\uE425")
    val TimerOff = MaterialSymbol("\uE426")
    val Topic = MaterialSymbol("\uF1C8")
    val Translate = MaterialSymbol("\uE8E2")
    val TravelExplore = MaterialSymbol("\uE2DB")
    val Tune = MaterialSymbol("\uE429")
    val Upload = MaterialSymbol("\uF09B")
    val VideoLibrary = MaterialSymbol("\uE04A")
    val VideoSettings = MaterialSymbol("\uEA75")
    val Videocam = MaterialSymbol("\uE04B")
    val VideocamOff = MaterialSymbol("\uE04C")
    val Visibility = MaterialSymbol("\uE8F4")
    val VisibilityOff = MaterialSymbol("\uE8F5")
    val Warning = MaterialSymbol("\uF083")
    val Work = MaterialSymbol("\uE943")
    val ZoomOutMap = MaterialSymbol("\uE56B")

    object AutoMirrored {
        val ArrowBack = MaterialSymbol("\uE5C4", autoMirror = true)
        val ArrowForward = MaterialSymbol("\uE5C8", autoMirror = true)
        val ArrowForwardIos = MaterialSymbol("\uE5E1", autoMirror = true)
        val Article = MaterialSymbol("\uEF42", autoMirror = true)
        val Chat = MaterialSymbol("\uE0C9", autoMirror = true)
        val ContactSupport = MaterialSymbol("\uE94C", autoMirror = true)
        val DriveFileMove = MaterialSymbol("\uE9A1", autoMirror = true)
        val ExitToApp = MaterialSymbol("\uE879", autoMirror = true)
        val Feed = MaterialSymbol("\uF009", autoMirror = true)
        val FormatListBulleted = MaterialSymbol("\uE241", autoMirror = true)
        val Forward = MaterialSymbol("\uF57A", autoMirror = true)
        val InsertDriveFile = MaterialSymbol("\uE66D", autoMirror = true)
        val KeyboardArrowLeft = MaterialSymbol("\uE314", autoMirror = true)
        val KeyboardArrowRight = MaterialSymbol("\uE315", autoMirror = true)
        val Label = MaterialSymbol("\uE893", autoMirror = true)
        val List = MaterialSymbol("\uE896", autoMirror = true)
        val Logout = MaterialSymbol("\uE9BA", autoMirror = true)
        val Message = MaterialSymbol("\uE0C9", autoMirror = true)
        val OpenInNew = MaterialSymbol("\uE89E", autoMirror = true)
        val PlaylistAdd = MaterialSymbol("\uE03B", autoMirror = true)
        val Send = MaterialSymbol("\uE163", autoMirror = true)
        val ShowChart = MaterialSymbol("\uE6E1", autoMirror = true)
        val ViewList = MaterialSymbol("\uE8EF", autoMirror = true)
        val VolumeOff = MaterialSymbol("\uE04F", autoMirror = true)
        val VolumeUp = MaterialSymbol("\uE050", autoMirror = true)
    }
}
