/*
 * Copyright (c) 2025 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.quartz.marmot.mls

import com.vitorpamplona.quartz.TestResourceLoader
import com.vitorpamplona.quartz.marmot.mls.codec.TlsReader
import com.vitorpamplona.quartz.marmot.mls.framing.MlsMessage
import com.vitorpamplona.quartz.marmot.mls.framing.WireFormat
import com.vitorpamplona.quartz.marmot.mls.group.MlsGroup
import com.vitorpamplona.quartz.marmot.mls.messages.KeyPackageBundle
import com.vitorpamplona.quartz.marmot.mls.messages.MlsKeyPackage
import com.vitorpamplona.quartz.nip01Core.core.JsonMapper
import com.vitorpamplona.quartz.nip01Core.core.hexToByteArray
import com.vitorpamplona.quartz.nip01Core.core.toHexKey
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Interop test against a Welcome authored by ts-mls — the TypeScript MLS
 * implementation that powers marmot-ts (the Marmot client for browsers /
 * Node / Bun / Deno). ts-mls is a completely independent codebase from
 * OpenMLS (MDK's backend), so a clean pass here means Amethyst agrees
 * byte-for-byte with two MLS implementations on every crypto surface
 * Marmot touches.
 *
 * Vector is regenerated by `quartz/tools/tsmls-vector-gen`.
 */
class TsMlsWelcomeInteropTest {
    @Serializable
    private data class TsMlsVector(
        @SerialName("cipher_suite") val cipherSuite: Int,
        val description: String,
        val joiner: Joiner,
        val committer: Committer,
        val welcome: String,
        val exporter: Exporter,
        @SerialName("app_messages_alice_to_bob")
        val appMessages: List<AppMessage> = emptyList(),
    )

    @Serializable
    private data class AppMessage(
        val plaintext: String,
        @SerialName("private_message") val privateMessage: String,
    )

    @Serializable
    private data class Joiner(
        @SerialName("init_priv") val initPriv: String,
        @SerialName("encryption_priv") val encryptionPriv: String,
        @SerialName("signature_priv") val signaturePriv: String,
        @SerialName("signature_pub") val signaturePub: String,
        @SerialName("key_package") val keyPackage: String,
        @SerialName("key_package_raw") val keyPackageRaw: String,
    )

    @Serializable
    private data class Committer(
        @SerialName("signer_pub") val signerPub: String,
    )

    @Serializable
    private data class Exporter(
        val label: String,
        val context: String,
        val length: Int,
        val secret: String,
    )

    private val vector: TsMlsVector =
        JsonMapper.jsonInstance.decodeFromString<TsMlsVector>(
            TestResourceLoader().loadString("mls/tsmls-welcome.json"),
        )

    @Test
    fun testTsMlsKeyPackageRoundTripAndSignature() {
        assertEquals(1, vector.cipherSuite)

        val kpMsg = MlsMessage.decodeTls(TlsReader(vector.joiner.keyPackage.hexToByteArray()))
        assertEquals(WireFormat.KEY_PACKAGE, kpMsg.wireFormat)

        val kp = MlsKeyPackage.decodeTls(TlsReader(kpMsg.payload))
        assertContentEquals(
            vector.joiner.keyPackageRaw.hexToByteArray(),
            kp.toTlsBytes(),
            "Inner KeyPackage bytes should round-trip",
        )
        assertTrue(kp.verifySignature(), "ts-mls-authored KeyPackage signature must verify")
    }

    @Test
    fun testProcessTsMlsWelcomeAndDeriveExporterSecret() {
        val kpMsg = MlsMessage.decodeTls(TlsReader(vector.joiner.keyPackage.hexToByteArray()))
        val kp = MlsKeyPackage.decodeTls(TlsReader(kpMsg.payload))

        // Amethyst's Ed25519 expects seed || pub (64 bytes); the generator
        // emits the 32-byte seed and pub separately.
        val sigPriv =
            vector.joiner.signaturePriv.hexToByteArray() +
                vector.joiner.signaturePub.hexToByteArray()

        val bundle =
            KeyPackageBundle(
                keyPackage = kp,
                initPrivateKey = vector.joiner.initPriv.hexToByteArray(),
                encryptionPrivateKey = vector.joiner.encryptionPriv.hexToByteArray(),
                signaturePrivateKey = sigPriv,
            )

        val group = MlsGroup.processWelcome(vector.welcome.hexToByteArray(), bundle)

        val ourExporter =
            group.exporterSecret(
                label = vector.exporter.label,
                context = vector.exporter.context.hexToByteArray(),
                length = vector.exporter.length,
            )
        assertEquals(
            vector.exporter.secret,
            ourExporter.toHexKey(),
            "MLS-Exporter disagreement post-join against ts-mls",
        )
        assertNotNull(group, "processWelcome returned null")
    }

    @Test
    fun testBobDecryptsTsMlsApplicationMessagesFromAlice() {
        assertTrue(
            vector.appMessages.isNotEmpty(),
            "tsmls-welcome.json should ship at least one app_messages_alice_to_bob entry",
        )

        val kpMsg = MlsMessage.decodeTls(TlsReader(vector.joiner.keyPackage.hexToByteArray()))
        val kp = MlsKeyPackage.decodeTls(TlsReader(kpMsg.payload))
        val sigPriv =
            vector.joiner.signaturePriv.hexToByteArray() +
                vector.joiner.signaturePub.hexToByteArray()
        val bundle =
            KeyPackageBundle(
                keyPackage = kp,
                initPrivateKey = vector.joiner.initPriv.hexToByteArray(),
                encryptionPrivateKey = vector.joiner.encryptionPriv.hexToByteArray(),
                signaturePrivateKey = sigPriv,
            )

        val bob = MlsGroup.processWelcome(vector.welcome.hexToByteArray(), bundle)

        for ((idx, msg) in vector.appMessages.withIndex()) {
            val decrypted = bob.decrypt(msg.privateMessage.hexToByteArray())
            assertContentEquals(
                msg.plaintext.hexToByteArray(),
                decrypted.content,
                "ts-mls application message $idx plaintext mismatch",
            )
        }
    }
}
