"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files:
  - source: amethyst/src/main/res/values/strings.xml
    translation: amethyst/src/main/res/values-%android_code%/%original_file_name%
    type: android
    skip_untranslated_strings: true
    languages_mapping:
      android_code:
        ar: ar
        cs: cs
        de: de
        eo: eo
        es: es
        fa: fa
        fr: fr
        hu: hu
        in: in
        ja: ja
        nl: nl
        ru: ru
        ta: ta
        th: th
        tr: tr
        uk: uk
        zh: zh