/*
 * Copyright (c) 2025 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.quartz.cordn.interop

import com.vitorpamplona.quartz.contextvm.cep04Encryption.CvmGiftWrap
import com.vitorpamplona.quartz.contextvm.cep04Encryption.EncryptionMode
import com.vitorpamplona.quartz.contextvm.fixture.CvmFixtureServer
import com.vitorpamplona.quartz.contextvm.fixture.InMemoryRelayPool
import com.vitorpamplona.quartz.contextvm.mcp.CvmMcpClient
import com.vitorpamplona.quartz.contextvm.transport.CvmTransport
import com.vitorpamplona.quartz.contextvm.transport.DualSigner
import com.vitorpamplona.quartz.cordn.fixture.CordnFixtureCoordinator
import com.vitorpamplona.quartz.cordn.spec00Coordinator.AvailableKeyPackage
import com.vitorpamplona.quartz.cordn.spec00Coordinator.ConsumedJoinRequestRef
import com.vitorpamplona.quartz.cordn.spec00Coordinator.ConsumedWelcomeRef
import com.vitorpamplona.quartz.cordn.spec00Coordinator.CoordinatorClient
import com.vitorpamplona.quartz.cordn.spec00Coordinator.CoordinatorMethod
import com.vitorpamplona.quartz.cordn.spec00Coordinator.GroupMessage
import com.vitorpamplona.quartz.cordn.spec00Coordinator.JoinRequest
import com.vitorpamplona.quartz.cordn.spec00Coordinator.PendingWelcome
import com.vitorpamplona.quartz.cordn.spec00Coordinator.PostedMessage
import com.vitorpamplona.quartz.cordn.spec00Coordinator.PublishedKeyPackage
import com.vitorpamplona.quartz.cordn.spec00Coordinator.TakenKeyPackage
import com.vitorpamplona.quartz.nip01Core.crypto.KeyPair
import com.vitorpamplona.quartz.nip01Core.signers.NostrSignerInternal
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.yield
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * [CoordinatorClient] against cordn's own wire contracts.
 *
 * `resources/cordn/coordinator-contracts.json` is generated by
 * `quartz/tools/cordn-vector-gen` from **`@cordn/core`** (MIT) — the package
 * the reference coordinator and client both import. Every payload in it was
 * accepted by their zod schema, and every `rejects` entry was refused by it.
 *
 * So this suite asks the two questions our own fixture cannot: does the JSON
 * we put on the wire match what their coordinator parses, and can we read what
 * theirs sends back? Both directions run through the real ContextVM transport,
 * so a regression in argument assembly, field naming or result parsing fails
 * here rather than against a live coordinator.
 *
 * What it does NOT cover is the coordinator's behaviour — ordering, cursor
 * assignment, admission control. That needs Tier B, which is blocked; see
 * `quartz/plans/2026-09-17-cordn-interop.md` §7.
 */
class CoordinatorContractVectorTest {
    private val vectors: JsonObject =
        Json
            .parseToJsonElement(
                checkNotNull(CoordinatorContractVectorTest::class.java.getResourceAsStream("/cordn/coordinator-contracts.json")) {
                    "missing cordn contract vectors"
                }.use { it.readBytes() }
                    .decodeToString(),
            ).jsonObject

    private fun contract(method: String): JsonObject = vectors["contracts"]!!.jsonObject[method]!!.jsonObject

    private fun input(
        method: String,
        key: String = "input",
    ): JsonObject = contract(method)[key]!!.jsonObject

    private fun output(
        method: String,
        key: String = "output",
    ): JsonObject = contract(method)[key]!!.jsonObject

    private val relays = InMemoryRelayPool()
    private val serverSigner = NostrSignerInternal(KeyPair())
    private val stableSigner = NostrSignerInternal(KeyPair())
    private val ephemeralSigner = NostrSignerInternal(KeyPair())
    private val plaintext = CvmGiftWrap(encryptionMode = EncryptionMode.DISABLED)
    private val coordinator = CordnFixtureCoordinator()

    private val client =
        CoordinatorClient(
            CvmMcpClient(
                CvmTransport(
                    relays = relays,
                    signers = DualSigner(stableSigner, ephemeralSigner),
                    serverPubKey = serverSigner.pubKey,
                    crypto = plaintext,
                ),
            ),
        )

    private fun serve() =
        CvmFixtureServer(
            relays = relays,
            signer = serverSigner,
            crypto = plaintext,
            injectClientPubkey = true,
            handler = coordinator::handle,
        ).also { it.start() }

    /** Runs [block] while pumping the fixture, since the relay callback cannot suspend. */
    private suspend fun <T> driving(block: suspend () -> T): T =
        coroutineScope {
            val server = serve()
            val work = async { block() }
            while (!work.isCompleted) {
                yield()
                server.pump()
                yield()
            }
            work.await()
        }

    /** The arguments the coordinator saw for [method], which must be its only call. */
    private fun sent(method: String): JsonObject {
        val calls = coordinator.calls.filter { it.method == method }
        assertEquals(1, calls.size, "expected exactly one $method call, saw ${coordinator.calls.map { it.method }}")
        return calls.single().arguments
    }

    private suspend fun scripted(
        method: String,
        result: JsonObject,
        block: suspend () -> Unit,
    ) {
        coordinator.scriptedResults[method] = result
        driving(block)
    }

    // ---- what we send ----------------------------------------------------

    @Test
    fun `kp_publish arguments match cordn's schema`() =
        runTest {
            driving { client.publishKeyPackage("1f".repeat(16), "AAECAwQFBgc=") }
            assertEquals(input("kp_publish"), sent("kp_publish"))
        }

    @Test
    fun `kp_remove arguments match cordn's schema`() =
        runTest {
            driving { client.removeKeyPackages(listOf("1f".repeat(16), "2e".repeat(16))) }
            assertEquals(input("kp_remove"), sent("kp_remove"))
        }

    @Test
    fun `kp_take arguments match cordn's schema`() =
        runTest {
            scripted("kp_take", output("kp_take", "emptyOutput")) { client.takeKeyPackage("1f".repeat(16)) }
            assertEquals(input("kp_take"), sent("kp_take"))
        }

    @Test
    fun `welcome_store arguments match cordn's schema, with and without a cursor`() =
        runTest {
            driving {
                client.storeWelcome("b".repeat(64), "2e".repeat(16), "V2VsY29tZQ==", after = 12)
            }
            assertEquals(input("welcome_store"), sent("welcome_store"))

            coordinator.calls.clear()
            driving { client.storeWelcome("b".repeat(64), "2e".repeat(16), "V2VsY29tZQ==") }
            assertEquals(input("welcome_store", "inputWithoutAfter"), sent("welcome_store"))
        }

    @Test
    fun `welcome_take omits consumed when there is nothing to retire`() =
        runTest {
            driving { client.takeWelcomes() }
            assertEquals(input("welcome_take"), sent("welcome_take"))

            coordinator.calls.clear()
            driving { client.takeWelcomes(listOf(ConsumedWelcomeRef("1f".repeat(16), 1757000000L))) }
            assertEquals(input("welcome_take", "inputWithConsumed"), sent("welcome_take"))
        }

    @Test
    fun `join_request arguments match cordn's schema`() =
        runTest {
            val gid = "6d1f0f6a-2a3e-4f2c-9a1d-7c6b5e4d3a21"
            driving { client.storeJoinRequest(gid, "1f".repeat(16)) }
            assertEquals(input("join_request_store"), sent("join_request_store"))

            coordinator.calls.clear()
            driving { client.takeJoinRequests(listOf(gid)) }
            assertEquals(input("join_request_take_many"), sent("join_request_take_many"))

            coordinator.calls.clear()
            driving {
                client.takeJoinRequests(listOf(gid), listOf(ConsumedJoinRequestRef(gid, "b".repeat(64), 1757000400L)))
            }
            assertEquals(input("join_request_take_many", "inputWithConsumed"), sent("join_request_take_many"))
        }

    @Test
    fun `msg_post arguments match cordn's schema`() =
        runTest {
            driving { client.postMessage("6d1f0f6a-2a3e-4f2c-9a1d-7c6b5e4d3a21", "c2VhbGVk") }
            assertEquals(input("msg_post"), sent("msg_post"))
        }

    @Test
    fun `a first fetch omits after entirely rather than sending zero`() =
        runTest {
            // `after` is typed as a number, so 0 is a real cursor, not "from
            // the start" -- sending it would silently skip the first message.
            val gid = "6d1f0f6a-2a3e-4f2c-9a1d-7c6b5e4d3a21"
            driving { client.fetchMessages(mapOf(gid to null)) }
            assertEquals(input("msg_fetch_many"), sent("msg_fetch_many"))

            coordinator.calls.clear()
            driving { client.fetchMessages(mapOf(gid to 42L)) }
            assertEquals(input("msg_fetch_many", "inputWithCursor"), sent("msg_fetch_many"))
        }

    // ---- what we read ----------------------------------------------------

    @Test
    fun `kp_publish result parses`() =
        runTest {
            lateinit var seen: PublishedKeyPackage
            scripted("kp_publish", output("kp_publish")) {
                seen = client.publishKeyPackage("1f".repeat(16), "AAECAwQFBgc=")
            }
            assertEquals("1f".repeat(16), seen.keyPackageRef)
            assertEquals(false, seen.lastResort)
            assertEquals(1757000000L, seen.at)
        }

    @Test
    fun `kp_list result parses, last_resort and all`() =
        runTest {
            lateinit var seen: List<AvailableKeyPackage>
            scripted("kp_list", output("kp_list")) { seen = client.listKeyPackages() }
            assertEquals(2, seen.size)
            assertEquals("a".repeat(64), seen[0].pubKey)
            assertEquals(false, seen[0].lastResort)
            assertEquals(true, seen[1].lastResort)
            assertEquals(1757000100L, seen[1].at)
        }

    @Test
    fun `kp_take result carries the publication event, and a null one means nothing held`() =
        runTest {
            lateinit var taken: TakenKeyPackage
            scripted("kp_take", output("kp_take")) { taken = client.takeKeyPackage("2e".repeat(16))!! }
            assertEquals("b".repeat(64), taken.pubKey)
            assertEquals(true, taken.lastResort)
            assertEquals(25910, taken.publicationEvent.kind)
            // Read back out of the signed payload, not from a sibling field.
            assertEquals("AAECAwQFBgc=", taken.keyPackageBase64())

            coordinator.calls.clear()
            coordinator.scriptedResults.clear()
            var empty: TakenKeyPackage? = null
            scripted("kp_take", output("kp_take", "emptyOutput")) { empty = client.takeKeyPackage("2e".repeat(16)) }
            assertNull(empty, "`keyPackage: null` means the coordinator holds nothing, not an error")
        }

    @Test
    fun `welcome_take result parses, including the optional resume cursor`() =
        runTest {
            lateinit var seen: List<PendingWelcome>
            scripted("welcome_take", output("welcome_take")) { seen = client.takeWelcomes() }
            assertEquals(2, seen.size)
            assertEquals(12L, seen[0].after)
            assertNull(seen[1].after, "`after` is optional; absent must not become 0")
            assertEquals("V2VsY29tZQ==", seen[0].welcomeBase64)
        }

    @Test
    fun `join_request_take_many result parses, gid and all`() =
        runTest {
            lateinit var seen: List<JoinRequest>
            scripted("join_request_take_many", output("join_request_take_many")) {
                seen = client.takeJoinRequests(listOf("6d1f0f6a-2a3e-4f2c-9a1d-7c6b5e4d3a21"))
            }
            assertEquals(1, seen.size)
            // The single-group variant of this record has no `gid`; the many
            // variant does, and we read the many one.
            assertEquals("6d1f0f6a-2a3e-4f2c-9a1d-7c6b5e4d3a21", seen[0].gid)
            assertEquals("b".repeat(64), seen[0].pubKey)
        }

    @Test
    fun `msg_post and msg_fetch_many results parse`() =
        runTest {
            lateinit var posted: PostedMessage
            scripted("msg_post", output("msg_post")) {
                posted = client.postMessage("6d1f0f6a-2a3e-4f2c-9a1d-7c6b5e4d3a21", "c2VhbGVk")
            }
            assertEquals(42L, posted.cursor)

            coordinator.calls.clear()
            coordinator.scriptedResults.clear()
            lateinit var fetched: List<GroupMessage>
            scripted("msg_fetch_many", output("msg_fetch_many")) {
                fetched = client.fetchMessages(mapOf("6d1f0f6a-2a3e-4f2c-9a1d-7c6b5e4d3a21" to 42L))
            }
            assertEquals(listOf(43L, 44L), fetched.map { it.cursor })
            assertEquals("c2VhbGVkLTE=", fetched[0].sealedBase64)
        }

    @Test
    fun `every coordinator tool name matches cordn's own table`() =
        runTest {
            val theirs =
                vectors["methods"]!!
                    .jsonObject.values
                    .map { it.toString().trim('"') }
                    .toSet()
            val ours = CoordinatorMethod.entries.map { it.wire }.toSet()
            assertEquals(theirs, ours, "the tool name set must match cordn's COORDINATOR_METHODS exactly")
            assertTrue(theirs.size == 11)
        }
}
