/*
 * Copyright (c) 2025 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.quartz.cyberspace.deck0003Sno

/**
 * `cyberspace-neon-256`, the palette an object's colour indices name when it
 * carries no `palette` of its own (DECK-0003 Appendix C, normative).
 *
 * The layout is arithmetic rather than a list to memorise:
 * - `0..191`   24 hues of 8 steps; hue `h` step `s` is `h * 8 + s`, step 0 darkest.
 * - `192..223` 32 steels, black to white, faintly cyan.
 * - `224..255` 32 signatures: the client's instrument colours, the six sRGB gamut
 *              corners, six neon staples and six deep grounds.
 *
 * Transcribed from `decks/sno-palette.json` in the cyberspace repository
 * (`"built": "2026-09-16"`), which is generated by `decks/sno-palette.mjs`.
 * Generated here rather than typed: [SnoBuiltInPaletteTest] pins the documented
 * anchors so a bad paste cannot ship silently.
 */
object SnoBuiltInPalette {
    /** The registered name of this palette, the only one DECK-0003 §1.3a defines. */
    const val NAME = "cyberspace-neon-256"

    private const val HEX =
        "003632004d49006562007e7d00979900b2b800cdd700e8f9" + // 0
            "003538004c5100636d007c8a0095a900afca00c9ed6fdfff" + // 8
            "00343f004a5a0061780079980092ba00abdf34c4ff93d8ff" + // 16
            "003346004865005e860075ab008dd200a4fd6ebcffa7d3ff" + // 24
            "00305200447600589e006ccc017fff5a9bff8bb5ffb5ceff" + // 32
            "00266d002cac1902ff374fff5a73ff7e92ffa1aeffc3c9ff" + // 40
            "2200883700b75000e76837ff8064ff9b86ffb6a5ffd0c4ff" + // 48
            "3500794f00a36b00cd8b00f8a24bffb875ffcd9affe1bcff" + // 56
            "4200695f008d7f00b1a200d5c600f8dd53ffed84fff9afff" + // 64
            "4b00586b00768e0094b200b1d900cdff1ae7ff7de2ffb1e6" + // 72
            "52004674005f980077be008ee600a4ff45b4ff87c0ffb5d2" + // 80
            "5700357a00489f005ac6006bee007bff538dff8ca6ffb7c2" + // 88
            "5a00247e0031a3003dcb0047f4004eff5b6aff908effb9b4" + // 96
            "5c0010800014a60013ce0006f22400ff613eff9375ffbba5" + // 104
            "561200752200943300b44600d45a00f47000ff9652ffbd93" + // 112
            "4b1f00683100854300a25700c06d00de8300fc9b00ffc077" + // 120
            "4426005e3800794c00946100b07800cc8f00e7a800ffc333" + // 128
            "3e2a00563d006e5300876900a08100b99900d2b300ebce00" + // 136
            "372d004d42006358007970008f8800a5a300b9be00cdda00" + // 144
            "2f3000424600555e0067770077910087ad0094ca009fe800" + // 152
            "243400314b003d6400457f00499b0045b9002cd90000f837" + // 160
            "073900005108006a1f008436009f4e00ba6700d68200f39e" + // 168
            "00381e00503000684400825b009c7300b78d00d3a900efc6" + // 176
            "00372a004e3f00665600806e009a8900b4a500d0c200ece1" + // 184
            "010101020203050606090b0c0f121315191a1b2021222728" + // 192
            "282e302f3638373e403e4648454e504d5658555e605d6769" + // 200
            "666f716e787a77808380898c899294939b9d9ca4a6a6adaf" + // 208
            "b0b6b8babfc1c4c9caced2d3d8dcdce3e5e6eeefeff8f8f8" + // 216
            "000000ffffff00e5ffff3b6bf7931a52e39fc8f5ff6f8ea0" + // 224
            "1d354705070dff00ff00ff0000ffffffff00ff00000000ff" + // 232
            "39ff14ff6ec77df9ffb026fffffb00ff330000ff9fff007f" + // 240
            "4d4dffffd3000a0f1a12182a1a0f240f1f1c2410161c1c0f" // 248

    /** 256 opaque ARGB colours, index-aligned with the sheet in Appendix C. */
    val COLORS: IntArray =
        IntArray(256) { i ->
            val at = i * 6
            val r = HEX.substring(at, at + 2).toInt(16)
            val g = HEX.substring(at + 2, at + 4).toInt(16)
            val b = HEX.substring(at + 4, at + 6).toInt(16)
            (0xFF shl 24) or (r shl 16) or (g shl 8) or b
        }
}
