/*
 * Copyright (c) 2025 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.quartz.marmot.appComponents

import com.vitorpamplona.quartz.TestResourceLoader
import com.vitorpamplona.quartz.marmot.appComponents.accountIdentityProof.AccountIdentityProofV2
import com.vitorpamplona.quartz.marmot.mip01Groups.MlsCiphersuite
import com.vitorpamplona.quartz.nip01Core.core.JsonMapper
import com.vitorpamplona.quartz.nip01Core.core.hexToByteArray
import com.vitorpamplona.quartz.nip01Core.core.toHexKey
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Validates the account-identity proofs in `marmot-current-profile.json`,
 * generated by `quartz/tools/mdk-vector-gen`'s `marmot-profile-gen` against the
 * OpenMLS fork MDK builds on.
 *
 * `AccountIdentityProofV2Test` proves we match the spec's published fixture.
 * This proves we match proofs produced by a *separate implementation* of that
 * spec, for randomly generated keys — which is the property that actually
 * matters for interop, and the one a fixed vector cannot establish.
 *
 * Everything else this vector carries (the `app_data_dictionary` framing, the
 * Welcome, the Add commit) is Stage 1/3 work; the assertions here stay on the
 * proof component and the registry ids so the test is meaningful today rather
 * than aspirational.
 */
class MarmotCurrentProfileVectorTest {
    @Serializable
    private data class Proof(
        val component: String,
        @SerialName("created_at") val createdAt: Long,
        @SerialName("event_id") val eventId: String,
        val signature: String,
    )

    @Serializable
    private data class Party(
        @SerialName("account_pubkey") val accountPubKey: String,
        @SerialName("signature_pub") val signaturePub: String,
        @SerialName("leaf_dictionary") val leafDictionary: Map<String, String>,
        @SerialName("account_identity_proof") val proof: Proof,
    )

    @Serializable
    private data class ComponentIds(
        @SerialName("app_components") val appComponents: String,
        @SerialName("safe_aad") val safeAad: String,
        @SerialName("last_resort_key_package") val lastResort: String,
        @SerialName("group_profile_v1") val groupProfile: String,
        @SerialName("admin_policy_v1") val adminPolicy: String,
        @SerialName("nostr_routing_v1") val nostrRouting: String,
        @SerialName("account_identity_proof_v2") val accountIdentityProof: String,
        @SerialName("group_lifecycle_v1") val groupLifecycle: String,
    )

    @Serializable
    private data class Vector(
        @SerialName("cipher_suite") val cipherSuite: Int,
        @SerialName("signature_scheme") val signatureScheme: Int,
        val profile: String,
        @SerialName("component_ids") val componentIds: ComponentIds,
        val committer: Party,
        val joiner: Party,
    )

    private val vector: Vector =
        JsonMapper.jsonInstance.decodeFromString<Vector>(
            TestResourceLoader().loadString("mls/marmot-current-profile.json"),
        )

    private val ciphersuite = MlsCiphersuite.DEFAULT

    private fun assertProofHolds(
        label: String,
        party: Party,
    ) {
        val leafKey = party.signaturePub.hexToByteArray()

        assertEquals(
            party.proof.eventId,
            AccountIdentityProofV2
                .proofEventId(party.accountPubKey, party.proof.createdAt, ciphersuite, leafKey)
                .toHexKey(),
            "$label: our kind-450 event id must match the generator's",
        )

        assertEquals(
            AccountIdentityProofV2.Result.VALID,
            AccountIdentityProofV2.validate(
                componentData = party.proof.component.hexToByteArray(),
                credentialIdentity = party.accountPubKey.hexToByteArray(),
                mlsSignatureKey = leafKey,
                ciphersuite = ciphersuite,
            ),
            "$label: externally generated proof must validate",
        )

        val fromDictionary = party.leafDictionary[AppComponentIds.toHex(AppComponentIds.ACCOUNT_IDENTITY_PROOF_V2)]
        assertNotNull(fromDictionary, "$label: leaf dictionary must carry a 0x8009 entry")
        assertEquals(
            party.proof.component,
            fromDictionary,
            "$label: the 0x8009 dictionary entry is the proof component verbatim",
        )
    }

    @Test
    fun theVectorIsACurrentProfileGroupOnOurDefaultCiphersuite() {
        assertEquals("current", vector.profile)
        assertEquals(ciphersuite.code, "0x${vector.cipherSuite.toString(16).padStart(4, '0')}")
        assertEquals(ciphersuite.signatureScheme, "0x${vector.signatureScheme.toString(16).padStart(4, '0')}")
    }

    @Test
    fun ourRegistryIdsMatchTheGeneratorRegistry() {
        val ids = vector.componentIds
        assertEquals(ids.appComponents, AppComponentIds.toHex(AppComponentIds.APP_COMPONENTS))
        assertEquals(ids.safeAad, AppComponentIds.toHex(AppComponentIds.SAFE_AAD))
        assertEquals(ids.lastResort, AppComponentIds.toHex(AppComponentIds.LAST_RESORT_KEY_PACKAGE))
        assertEquals(ids.groupProfile, AppComponentIds.toHex(AppComponentIds.GROUP_PROFILE_V1))
        assertEquals(ids.adminPolicy, AppComponentIds.toHex(AppComponentIds.ADMIN_POLICY_V1))
        assertEquals(ids.nostrRouting, AppComponentIds.toHex(AppComponentIds.NOSTR_ROUTING_V1))
        assertEquals(ids.accountIdentityProof, AppComponentIds.toHex(AppComponentIds.ACCOUNT_IDENTITY_PROOF_V2))
        assertEquals(ids.groupLifecycle, AppComponentIds.toHex(AppComponentIds.GROUP_LIFECYCLE_V1))
    }

    @Test
    fun theCommitterProofValidates() = assertProofHolds("committer", vector.committer)

    @Test
    fun theJoinerProofValidates() = assertProofHolds("joiner", vector.joiner)

    @Test
    fun theTwoProofsAreNotInterchangeable() {
        // Different accounts AND different leaf keys, so this catches a
        // validator that ignored either binding.
        assertTrue(vector.committer.accountPubKey != vector.joiner.accountPubKey)
        assertTrue(vector.committer.signaturePub != vector.joiner.signaturePub)

        assertEquals(
            AccountIdentityProofV2.Result.CREDENTIAL_IDENTITY_MISMATCH,
            AccountIdentityProofV2.validate(
                vector.committer.proof.component
                    .hexToByteArray(),
                vector.joiner.accountPubKey.hexToByteArray(),
                vector.joiner.signaturePub.hexToByteArray(),
                ciphersuite,
            ),
        )
        assertEquals(
            AccountIdentityProofV2.Result.BAD_SIGNATURE,
            AccountIdentityProofV2.validate(
                vector.committer.proof.component
                    .hexToByteArray(),
                vector.committer.accountPubKey.hexToByteArray(),
                vector.joiner.signaturePub.hexToByteArray(),
                ciphersuite,
            ),
        )
    }

    @Test
    fun everyLeafDictionaryAdvertisesTheProofAndSafeAad() {
        // The dictionary decoder is Stage 1; assert the entry set here so a
        // regression in what the generator emits is caught early.
        for ((label, party) in listOf("committer" to vector.committer, "joiner" to vector.joiner)) {
            assertEquals(
                setOf("0x0001", "0x0002", "0x8009"),
                party.leafDictionary.keys,
                "$label: a member leaf carries the supported list, safe_aad, and the proof",
            )
        }
    }
}
