/*
 * Copyright (c) 2025 Vitor Pamplona
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package com.vitorpamplona.amethyst.commons.richtext

import com.vitorpamplona.amethyst.commons.model.EmptyTagList
import com.vitorpamplona.quartz.experimental.clink.pointers.OfferPriceType
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class ClinkOfferSegmentTest {
    // generated by @shocknet/clink-sdk@1.5.5 (see quartz ClinkInteropTest)
    private val offerFixed =
        "noffer1qszqqqzjpqpszqqzpphkven9wgkkjeqprpmhxue69uhhyetvv9ujuumgda3kkmn9wshxgetkqqs8ul5ug253hlh3n75jne0a5xmjur4urfxpzst88cnegg6ds6ka7nsx7zr9c"

    private fun words(text: String) =
        RichTextParser()
            .parseText(text, EmptyTagList, null)
            .paragraphs
            .flatMap { it.words }

    @Test
    fun detectsNofferInlineAsClinkOfferSegment() {
        val segment =
            words("Pay me here $offerFixed thanks")
                .filterIsInstance<ClinkOfferSegment>()
                .single()

        assertEquals(offerFixed, segment.segmentText)
        assertEquals("offer-id", segment.offer.pointer)
        assertEquals(OfferPriceType.FIXED, segment.offer.priceType)
        assertEquals(21000, segment.offer.price)
    }

    @Test
    fun malformedNofferIsNotDetected() {
        assertTrue(words("nope noffer1notvalidbech32 end").none { it is ClinkOfferSegment })
    }

    @Test
    fun plainTextHasNoOfferSegment() {
        assertTrue(words("just a normal sentence").none { it is ClinkOfferSegment })
    }
}
