name: Test/Build macOS

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test Quartz (gradle)
        run: ./gradlew :quartz:jvmTest --no-daemon --warn

      - name: Test Commons (gradle)
        run: ./gradlew :commons:jvmTest --no-daemon --warn

      - name: Test Desktop (gradle)
        run: ./gradlew :desktopApp:test --no-daemon --warn

      - name: Build Desktop distribution (gradle)
        run: ./gradlew :desktopApp:packageDistributionForCurrentOS --no-daemon --warn

      - name: Upload macOS distribution
        uses: actions/upload-artifact@v4
        with:
          name: Desktop-macOS
          path: desktopApp/build/compose/binaries/main/dmg/*.dmg

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports-macOS
          path: |
            quartz/build/reports/tests/
            commons/build/reports/tests/
            desktopApp/build/reports/tests/
